### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák javítása

### ISSUE THREAD

**Issue by Imdapro** [Imdapro/commons-rdf#2]
A kódon statikus ellenőrzést kell csinálnunk.

**Comment by Imdapro** [comment]
Készítek egy wiki oldalt:
[Wiki](https://github.com/Imdapro/commons-rdf/wiki/SonarQube-feladat)
A SonarQube-t használva futtatok egy vizsgálatot.

**Comment by TitanillaGats** [comment]
Commit: "made attribute transient"@2017. 04. 19. 14:46:29
Status: OK

Az RDFParser valóban nem szerializálható, így jobb, ha jelezzük a fordítónak is, hogy ne próbálja meg szerializálni adott esetben.

**Comment by TitanillaGats** [comment]
Commit: "replaced double quotes to simples"@2017. 04. 19. 14:47:53
Status: OK

Különösebben nem zavart, hogy egy karakter nem aposztrófban van, hanem idézőjelek között. Mivel a SonarQube szólt érte, megérte átírni. Érdemben nem változott ettől semmi.

**Comment by TitanillaGats** [comment]
Commit: "replaced Optional<> nullcheck to isPresent() check"@2017. 04. 19. 14:49:10
Status: BROKEN

Szerintem itt a SonarQube tévedett. Az Option<BlankNodeOrIRI> elnevezés is azt sugallja, hogy megengedett az üres Option() is, amit például az empty() függvény is szolgáltat. Így most az üres Option<> nem megengedett, pedig a null vizsgálattal az volt.

@Imdapro meg tudnád nézni, hogy nem néztem-e be valamit? Köszi!

**Comment by TitanillaGats** [comment]
Commit: "replaced null return to Optional.empty()"@2017. 04. 19. 14:50:20
Status: BROKEN

Szerintem ennél is fennáll, ugyanaz, mint az előzőnél. Esetünkben a null és az Option<null> nem egyenértékű (nyilván), és ezzel logikailag változtattunk a kódon. Nem tudhatjuk, hogy hol számítanak Option<null>-ra, ahol a null hibát okoz.

@kcsombi esetleg rá tudnál nézni? Nem ártana egy másodvélemény. Köszi!

**Comment by TitanillaGats** [comment]
Commit: "removed unnecessary IllegalArgumentException declarations"@2017. 04. 19. 14:56:18
Status: OK

Szép! A legjobb kód, amit meg sem írtak, szóval támogatom a felesleges (és félrevezető) dolgok kiszedését.

**Comment by TitanillaGats** [comment]
Commit: "replaced lambdas with method references"@2017. 04. 19. 14:57:52
Status: OK

Ez igazán csak szépítés: lambdák vagy metódus referenciák. Érdemben nem változott semmi.

**Comment by TitanillaGats** [comment]
Commit: "moved variables to their right places"@2017. 04. 19. 14:59:15
Status: OK

Igen, az osztály-szintű tagváltozók igenis legyenek az osztály elején definiálva.

**Comment by TitanillaGats** [comment]
Commit: "removed commented-out code"@2017. 04. 19. 15:20:59
Status: OK

Kikommentezett kódnak nincs helye, csak nagyon indokolt esetben és akkor is max rövid távon. Jó, hogy kikerült.

**Comment by TitanillaGats** [comment]
Commit: "removed unnecessary TODO"@2017. 04. 19. 15:21:58
Status: OK

Nem tudom, hogy egy TODO hogy lehet felesleges. Természeténél fogva azt jelzi, hogy ott valamit még csinálni kell. Így hacsak a SonarQube nem tudja értelmezni a szöveges igényt ami alapján meggyőződött arról, hogy a kódban megtörtént a kért változtatás, aligha dönthet úgy, hogy egy TODO felesleges. Rosszabb nem lett, mondjuk információt vesztettünk.

**Comment by TitanillaGats** [comment]
Commit: "removed commented-out code #2"@2017. 04. 19. 15:22:40
Status: OK

Nem használt kódnak nincs helye.

**Comment by TitanillaGats** [comment]
Commit: "removed unnecessary IllegalStateException declaration"@2017. 04. 19. 15:32:59
Status: OK

Korábban már volt egy ilyen commit másik osztályon. Támogatom hogy a nem valós állítás kikerült.

**Comment by micskeiz** [comment]
OK.

Jó, hogy nem fogadtátok el vakon a Sonar összes jelzését. 

Ha végeztetek a feladattal, akkor zárjátok le az issue-t.

**Comment by Imdapro** [comment]
Kijavítottuk a hibákat, amiket valóban hibának véltünk és ki tudtunk javítani. A kódminőségre már megfelelőt ír a Sonar.
