### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by Imdapro** [Imdapro/commons-rdf#3]
A kód egy részét ellenőrizzük manuálisan.

**Comment by TitanillaGats** [comment]
A megbeszéltek alapján létrehoztam a gitlab repot, amit itt találtok: https://TitanillaGats@gitlab.com/TitanillaGats/commons-rdf.git

**Comment by TitanillaGats** [comment]
Végeztem az AbstractRDFParser átnézévsével. Nem értem a tagváltozó miért lett függvényhívás, nem találtam hozzá értelmes commit üzenetet sem. Nálam egyébként nem is találja se függvényként, se tagváltozóként, pedig ami nálam van RDFSyntax fájl, abban létezik és tagváltozó.

**Comment by TitanillaGats** [comment]
Átnéztem a LiteralImpl osztályt is, én a sok replace-t lecserélném egy replaceAll-ra, ahogy a commentben ki is fejtettem.
Amit még hiányolok, az a comment a logikát is tartalmazó függvénynél... Néhol egy tagváltozó létét is 5 sorban taglalják, ahol pedig lenne is mit magyarázni, ott semmi.

**Comment by TitanillaGats** [comment]
Általános észrevétel: kommentek hiánya/túlhasználata, final és Impl használata mindenhol, semmi értelmes commit üzenet vagy issue hivatkozás
Felesleges helyeken is final jelző használata tagváltozók, paraméterek és függvények esetében. Nem látom a mögöttes koncepciót, azt viszont igen, hogy 5 hónapja történt és szisztematikusan eléjük írták, számomra "mert miért ne" indokkal.
A felesleges kommentek mellett a legrosszabb az értelmes kommentek hiánya. Az előző megszólalásomnál már kifejetettem, hogy mi is ezzel a problémám.
A másik általános észrevételem CleanCode elvekkel ütközik. Egyszerűen nem illik kódolni az osztályok nevét, ha semmi plusz információt nem hordoz. Ebben az esetben még megtévesztő is. Hiszen majdnem minden osztály nevében szerepel az Impl postfix, de ez nem jelenti azt, hogy amelyiknél nincs ott, az nem implementál valamit.

**Comment by TitanillaGats** [comment]
Types osztállyal is végeztem. Nekem annyira nem tetszett hogy görgetni kellett a lényegi tartalomért, a statikus típus-létrehozásokat lehet hogy külön osztályba tenném vagy valahogy máshogy csinálnám. Sokat kellett görgetni a tartalomért, de legalább volt komment.

**Comment by TitanillaGats** [comment]
Végignéztem az IRIImpl osztályt, egyedül a konstruktora nem tetszett. Tudják, hogy érvénytelen stringnél hiba dobódik, de el sem kapják és tovább sem dobják.

**Comment by Imdapro** [comment]
Az issue-hoz tartozó [wiki oldal](https://github.com/Imdapro/commons-rdf/wiki/Manu%C3%A1lis-k%C3%B3d-%C3%A1tvizsg%C3%A1l%C3%A1s-feladat)

**Comment by Imdapro** [comment]
Átnéztem, és helyesnek találtam TitanillaGats meglátásait.

**Comment by micskeiz** [comment]
Rendben, alapos volt a kód átnézése. Külön plusz, hogy még a GitLab-ot is kipróbáltátok közben.

**Comment by Imdapro** [comment]
Az átnézés sikeresen megtörtént.
